server:
  port: 9000

spring:
  application:
    name: gateway-service
  cloud:  # 网关配置    这样配置就代表走网关可以访问blog项目的链接（直接访问的，没有任何股过滤信息。）
    gateway:
      routes:
        - id : blog8084
          uri: lb://business-service
          predicates:
            - Path=/guonei/**
          filters: #解决使用服务名无法访问的问题。
            - StripPrefix=1
#      discovery: #开启微服务名字转发   也就是根据服务名去访问不同的项目
#        locator:
#          enabled: true

eureka:
  instance:
    hostname: gateway-service
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
