server:
  port: 9001

spring:
  application:
    name: business-service

eureka:
  instance:
    hostname: business-service
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/